### PR TITLE
Update README with detailed cli parser options

### PR DESCRIPTION
**Pull request by RobertDeRose**
Fixed an out-of-order issue by my edits.
Better description and added example for toType function

### CODE REVIEW

**Comment by RobertDeRose** [comment]
Closes #71

**Comment by RobertDeRose** [comment]
ping @chriso. Are you still active with this repo and if so, are you taking Pull Requests?

**Comment by chriso** [comment]
I am, sorry. This PR seems to include the commits from #72. Can I close that one?

**Comment by RobertDeRose** [comment]
Sorry yes, I did #72 before I did this one and didn't think to delete it or just add this to it.

**Comment by RobertDeRose** [comment]
Hey thanks for taking the pull request.  However, I see you didn't take the version bump, I was wondering why? Also wondering if you were going to push this to npm?  Thanks again.

**Comment by chriso** [comment]
I just pushed `0.10.0`.

**Comment by RobertDeRose** [comment]
Awesome!

**Pull request merged**
